[pytest]
testpaths = tests

markers =
    smoke: critical tests for basic application functionality
    regression: full regression test suite
    api: API tests
    database: database tests
    ui: UI tests

addopts = --tracing=retain-on-failure --screenshot=only-on-failure